### ISSUE TITLE
node.js engine update is not indicated, this should perhaps be a breaking change?

### ISSUE THREAD

**Issue by shazron** [gajus/eslint-plugin-jsdoc#1053]
Hello :)
Dependabot automatically lists updates for my repo dependencies and one of it is this plugin. Looking at the release notes there is no indication of this breaking change of node.js engine update in 43.0.7: https://github.com/gajus/eslint-plugin-jsdoc/compare/v43.0.7...main in any of the [Releases](https://github.com/gajus/eslint-plugin-jsdoc/releases) (no ref to #1034)

In my opinion this should have been communicated as a major version release? (somewhat following semver) Some of us have a longer transition period to drop support for node-14.

Thank you :)

**Comment by shazron** [comment]
Related #973

**Comment by brettz9** [comment]
Apologies. What with a number of breaking changes going on at the same time, and to issues with PR approvals, I failed to note the need to squash and format our commits for this change to indicate this was a breaking change. Since this project is presumably a dev dependency, I would hope you would be able to pin the version in your project without additional repercussions for now, but going forward, we will hopefully be more attuned to avoid such breakages. Closing but feel free to comment further as needed.
