### ISSUE TITLE
Question (docs?): `enableFixer` for certain rules

### ISSUE THREAD

**Issue by thernstig** [gajus/eslint-plugin-jsdoc#1072]
I just noticed that e.g. https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/no-blank-blocks.md#readme has an `enableFixer` rule.  It defaults to false.

It seems some rules have this. It is required to be set to `true` in order for `--fix` to work, at least that is how I interpret it (and when I tested it). Correct me if I am wrong.

Two questions:
1. How come it is not default set to `true`? It is what I would expect, but I bet there is a rationale to set it to default `false`.
2. Is this an option that is intended to be added to all rules to control where the rules, that can automatically fix faults, should do it or not when adding the `--fix` flag? If so should this general rule be documented in the main README.md at least close to the table showing what rules are fixable (with the wrench icon)?

With the caveat that I completely misunderstood its usage 😆

**Comment by brettz9** [comment]
> I just noticed that e.g. https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/no-blank-blocks.md#readme has an `enableFixer` rule. It defaults to false.
> 
> It seems some rules have this. It is required to be set to `true` in order for `--fix` to work, at least that is how I interpret it (and when I tested it). Correct me if I am wrong.

It must be set to `true` for it to work, though sometimes `true` is the default.

> 1. How come it is not default set to `true`? It is what I would expect, but I bet there is a rationale to set it to default `false`.

A number of rules set `enableFixer` to `true` by default, but this is set to `false` because it may become annoying for people working in an IDE with an auto-fixer that as soon as they type a JSDoc block to start typing in, and then save, it will be wiped away. Some may be ok with that, but it may be preferable to just have an error. It will show in the IDE that it must be completed (or removed), but no annoying disappearance.

> 2. Is this an option that is intended to be added to all rules to control where the rules, that can automatically fix faults, should do it or not when adding the `--fix` flag? 

Yes.

> If so should this general rule be documented in the main README.md at least close to the table showing what rules are fixable (with the wrench icon)?

Good idea. I've submitted #1073 for this.
