### ISSUE TITLE
With 46.4.2 match-description reports error when require-description is off

### ISSUE THREAD

**Issue by yvele** [gajus/eslint-plugin-jsdoc#1126]
## Expected behavior
`"jsdoc/require-description" : "off"` should overrule `"jsdoc/match-description"`

This works with v46.2.6 👍 
And does not work anymore with v46.4.2 👎 

## Actual behavior

I've juste updated my eslint-plugin-jsdoc dependency from v46.2.6 to v46.4.2 and now i have this error popping everywhere:

>  error  JSDoc description must not be empty  jsdoc/match-description

## ESLint Config

```js

  plugins : [
    "jsdoc"
  ],
  rules : {

    // Don't require a description
    "jsdoc/require-description" : "off",

    // Enforces a regular expression pattern on descriptions.
    "jsdoc/match-description" : ["error", {
      // The default is this basic expression to match English sentences
      // that does not necessarily ends with a dot
      matchDescription : "^([A-Z]|[`\\d_])[\\s\\S]"
    }]

}
```

## ESLint sample

```js
/**
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase
 * @returns {Function} Middleware function
 * @throws {ArgumentNullError}
 * @throws {ArgumentError}
 */
export default function isUpperCase() {
  ...
}
```

but also 🤔 

```js
/**
 * Validate that a string is all uppercase.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase
 * @returns {Function} Middleware function
 * @throws {ArgumentNullError}
 * @throws {ArgumentError}
 */
export default function isUpperCase() {
  ...
}
```

## Environment

- Node version: v18.15.0
- ESLint version v8.43.0
- `eslint-plugin-jsdoc` version: 46.4.2

**Comment by brettz9** [comment]
Thanks for the report.

First a point of clarification. With the exception of the marking of unused variables, ESLint rules should not influence one another, so despite appearances, `jsdoc/require-description` has never influenced `jsdoc/match-description`.

However, there were indeed some recent changes to `match-description` which made it more aggressive (and indeed too aggressive).

I submitted #1127 to stop reporting missing descriptions for `@throws` (and `@yields`) which was probably the source of your grief, so you might try 46.4.3 to see if you are satisfied with the changes.

Note that the `match-description` rule will still have the following new, more aggressive behaviors:

1. Enforce the default initial-caps regular expression on the following tags (unless one supplies one's own match for them on `tags`):  'description', 'summary', 'file', and 'classdesc'. Although `match-description` does not report missing descriptions for block descriptions (it only reports when a block description is present and fails to match), it does now expect descriptions to match if these tags are present at all, with the rationale that these tags should probably not be present if they are blank. The tags are also expected to follow the match-description desired sentence structure (e.g., initial caps) when a description is present.
2. Enforces a simple, non-empty regular expression on the following tags unless the new option `nonemptyTags` is set to `false`: 'copyright', 'example', 'see', 'todo'. It is figured that if these tags are present at all, they should not be empty, though they might not follow normal sentence structure so the check on them is just that some description exists.

For no. 2, this new functionality could admittedly have been placed in `require-description`, but I figured `require-description` could be kept more simple.

Feedback is welcome on whether the changes are still felt to be somehow too aggressive even with `throws` and `yields` now dropped. FWIW, the rationale for originally including these tags was that if one wanted more descriptive control as shown by enabling the rule, these tags could also use descriptions, but since the rule previously did not report errors when a description was entirely missing, this change ended up being too aggressive. We could still enforce the regular expression for these tags when only a description for them is present, but perhaps people might not care to have, e.g., upper-case sentences enforced with `throws` or `yields` even if they do want them for block descriptions.

**Comment by yvele** [comment]
ok @brettz9 thanks for the clarification.
So this change is breaking and should have been published as a v47 🙏 
How could I have the same behavior as I always had with eslint-plugin-jsdoc before this new "aggressive" change?
How could I have a regex enforcing the description layout but with an optional description?
Thank you

**Comment by yvele** [comment]
Oh yeah I didn't get it straight but yeah it's working fine with 46.4.3 👍 
Thank you @brettz9
