### ISSUE TITLE
Move settings to options

### ISSUE THREAD

**Issue by golopot** [gajus/eslint-plugin-jsdoc#216]
It is hard to find out which setting adheres to which rule. It is better to move settings specific to one rule to the option of that rule.

**Comment by brettz9** [comment]
Could you change the issue title to not be specific to `require-param`? I think it would be better in the case of most rules to allow for options instead of settings. (There may be a few though which interact across rules.)

**Comment by golopot** [comment]
It seems that only `require-param` and `check-examples` have accompanied settings.

**Comment by brettz9** [comment]
There are others; e.g., `valid-types` invokes `utils.isNamepathType` which, passes on the `checkSeesForNamepaths` setting, etc. It is a little harder to follow in the source because the settings are in iterateJsdoc and the rule pages typically interact with these settings through `utils`.

**Comment by brettz9** [comment]
Also `check-tag-names` has the setting `additionalTagNames` which only it uses, and `valid-types` has two settings (`allowEmptyNamepaths` and `checkSeesForNamepaths`) that only it uses.

The only setting that really is used across rules is `tagNamePreference` and I actually think we might change it so that it only works with `check-tag-names`, as the various require and param rules which use it are, because of it, failing to check for violations in non-preferred (or non-default) tags (e.g., if I prefer `@param`, but have a problem in `@arg`, it won't be caught). While this might be seen as a minor optimization if one knows one has no need to check for other synonyms, I think this is not worth it. But the option does make sense in `check-tag-names`.

**Comment by golopot** [comment]
What is the process for moving settings to options? I suggest we do it one-step in a major release: add options, stop reading settings, and warns to stderr in case a removed setting is set.

**Comment by brettz9** [comment]
Sounds like a fine approach to me... I have my hands pretty full now, but a PR would be welcome...

Bear in mind though re: breaking changes... As much as one doesn't wish to make breaking changes in any project, in a linting project, it can be as little total pain for a project to keep up with more frequent breaking changes and make a few incremental changes as it is to "rip off the bandage" and do it all at once, and with linting, breaking changes are far more likely (especially if one were to interpret every minor loosening or tightening as a breaking change).

With linting, particularly ESLint, one has good feedback about what is failing and why, so it doesn't generally take a lot of debugging and deep refactoring work that might be better done all at once as can be the case for non-linting API changes.

But doing it all at once makes sense, especially as the changes are related, and it is better to increase consistency with the API.

**Comment by golopot** [comment]
It will be great if someone can take up remaining part of this issue, that is, move settings of check-examples to options.

**Comment by brettz9** [comment]
I've started a branch to do so; just need to fix up the docs.

We might then see about removing the already-deprecated `allowOverrideWithoutParam`, `allowImplementsWithoutParam`, and `allowAugmentsExtendsWithoutParam` as well as changing the default of their replacements to `true`.
