### ISSUE TITLE
Incorrect error position and destructive autofix when newline-after-description is never

### ISSUE THREAD

**Issue by jaydenseric** [gajus/eslint-plugin-jsdoc#328]
When `newline-after-description` is `never`, the error position is wrongly placed amongst tags and the autofix (each time) destructively deletes the line/tag at the end of the block, without actually fixing the error:

![eslint-plugin-jsdoc-fix-bug-2](https://user-images.githubusercontent.com/1754873/61037325-2b08b880-a40e-11e9-96a7-c0ec17617b66.gif)

**Comment by jaydenseric** [comment]
I also noticed that sometimes when `newline-after-description` is `always`, the opposite can happen: Lots of new lines are inserted in the middle of the JSDoc block.

**Comment by brettz9** [comment]
Thanks for the report. In future issues, please paste the problematic jsdoc blocks.

**Comment by brettz9** [comment]
The issue in this case (for "always" or "never") was that we were looking for the last line out of the whole jsdoc block (including the tags) whose description *included*, rather than being an exact match for, the text, so in your example, the "A." description of `@prop a` was thought to be the last main description line, and thus the newline was added or removed after that line.

As with other fixer issues, this kind of mistake should be caught be applying a stringifier to fixed JSDoc JSON, rather than reimplementing string parsing for each fixer.
