### ISSUE TITLE
require-description-complete-sentence false positives

### ISSUE THREAD

**Issue by MaxMilton** [gajus/eslint-plugin-jsdoc#337]
Looks like commit https://github.com/gajus/eslint-plugin-jsdoc/commit/78f9b61b3a8e0a4c9e0496d79589c288f7f7d511 to fix https://github.com/gajus/eslint-plugin-jsdoc/issues/333 has introduced a regression.

`@example` tags contain code and should not be treated as a sentence. Since it looks like the rule runs on all JSDoc tags, maybe an option to disable the check for certain tags would be useful.

The autofix for the rule is quite annoying so a way to disable the autofix would be great too. It breaks things like changing `/** @jest-environment node */` to `/** @jest-environment Node */`, causing jest to fail.

Starting a line with a capital character also often trigger a false positive. This typically happens when using words which should be capitalised, e.g. names; JavaScript, TypeScript, ProductName. Could the logic be relaxed to only trigger if the previous line ends with a `.` or is a line break?

Abbreviation which contain `.`s also trigger false positives, e.g. `e.g. Text`.

**Comment by brettz9** [comment]
Regarding making the fixer optional and changing the logic, I've added a notation on #336, so that can be tracked there.

Regarding abbreviations, have you tried adding a comma, as in `e.g.,`? That is the standard way to write it anyways (and code using dots should be encapsulable within backticks).

As far as the first issue mentioned re: `@example`, I plan to add some logic shortly to avoid that by default, and I agree a blacklist option for other tags such as custom ones is a good idea.

**Comment by brettz9** [comment]
Actually, on further examination of the tags, I think we should implement with a `tags` whitelist (as we do with other rules), since there are many tags for which a description is not appropriate, e.g., `@author`, `@defaultvalue`, etc., though we can default to support some like `classdesc`, `summary` where it is likely desirable.
