### ISSUE TITLE
Document breaking changes for major versions (like v16.x.x)

### ISSUE THREAD

**Issue by Zearin** [gajus/eslint-plugin-jsdoc#414]
I just noticed the new release, but I visited this page and could not find a changelog.

Can you list any major breaking changes somewhere (where someone looking for the info can easily find it)?

**Comment by gajus** [comment]
https://github.com/gajus/eslint-plugin-jsdoc/releases

**Comment by Zearin** [comment]
Well, yes…I found that.  But the following description from v16.0.0…

> check-tag-names and other rules: Allowable values: jsdoc|typescript|closure

…doesn’t say much.  

What does “other rules” mean?  _Which_ rules?  Are there any recommendations for users who upgrade?

**Comment by gajus** [comment]
You can click through on the individual commits/ issues that are mentioned in the release log to learn implementation details and related discussion.

**Comment by Zearin** [comment]
Yes, I know.  That is true of any GitHub project.  But most choose to publish a changelog to make it easier for users to find what they're looking for.  

You have made it clear that this is not something you want users to easily do.

**Comment by brettz9** [comment]
There is no need for sharpness here. Gajus has employed a time-saving feature for developers on this free, open source project to which we contribute in our spare, unpaid time. Maintaining a change log requires extra time. You can just ask for clarification if the docs are not sufficient, or make a PR yourself to improve the docs that were included within the release commits. 

Also, not every project adds release notes pointing to commits; for some, you have to dig through the commit history and try to figure out which commits were tied to which release.

For my part, I apologize if these particular notes were not clear. Some of the details of the changes in this case are actually a bit obscure and not likely to impact users, though because of the atomic nature of how our release system automatically produces a release upon a single breaking change, it doesn't make clear that subsequent releases are actually related together.

(And with any linting project, it is not always clear on how to decide on what constitutes a "breaking change" anyways--even a "fix" could break one's CI but starting to fail on something which should have failed earlier.)

But to clarify the particular items that are breaking...

We now look to `settings.jsdoc.mode` to determine what a valid tag is (and since this mode didn't previously exist, the breaking change is that you will assume to be in plain "jsdoc" mode, rather than working in "typescript" or "closure").

The main significance of this is that if you try to use tags which are not part of jsdoc proper, like `@template`, you will get a warning unless you choose "closure" or "typescript" mode since this tag is not a part of standard jsdoc (similarly if you try to use a Closure-only tag like `@struct` and have no mode set or set it to "jsdoc" or "typescript").

FWIW, a more obscure change, which has no visible impact yet, is that the mode can be used to determine default preferred tag name, e.g., Closure indicates [`return`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#return-type-description) while jsdoc lists [`returns`](https://jsdoc.app/tags-returns.html) as the main item. However, our code is not indicating these preferences (at least not as of yet).

In the subsequent 16.1.0 release, the consequence is that we now don't bother to check the type component on tags where only a different mode allows a type, e.g., only Closure should have a type component for [`@private`](https://jsdoc.app/tags-private.html), but I treated this as a mere "feature" since it was released minutes after 16.0.0 and was related to the 16.0.0 change toward new behavior per mode.
