### ISSUE TITLE
Document one rule per file

### ISSUE THREAD

**Issue by zypA13510** [gajus/eslint-plugin-jsdoc#472]
As it currently stands, the README contains all the documentation of every rule. This makes it very long and hard to read. We could break them into separate files, and add an overview that links to each file.

Related: #365, #471

**Comment by brettz9** [comment]
Per https://github.com/gajus/eslint-plugin-jsdoc/pull/475#issuecomment-572405495 , it seems that splitting the docs has been nixed, so closing this issue.

However, feel free to file another issue to cover the desire for curating examples and/or collapsing examples (if I can get #499 working, I could perhaps add the collapsing code on sections where it was desired--though hopefully we can use the `open` attribute on `<details>` ( + `<summary>`) so it is expanded by default as otherwise there would be work to click to open the sections--adding the burden to those of on slow connections that we not only have to load a potentially slow single page, but we have to uncollapse it after it loads).
