### ISSUE TITLE
Plugin not working on my project

### ISSUE THREAD

**Issue by QuentinDela** [gajus/eslint-plugin-jsdoc#486]
Hello, 

I have this sample project 
https://github.com/QuentinDela/eslint-test

The linter doesn't trigger error event if its missing jsdocs.

What am I missing ?

Thanks

**Comment by brettz9** [comment]
Try changing to `"jsdoc/require-jsdoc": [1, {require: {FunctionExpression: true}}]`. The current default does not enforce for function expressions. However, since function expressions are often not very significant (e.g., for use within `forEach`), you could also refactor your code to express as a declaration, e.g., `function fn (a) {}`.

That should answer, but feel free to comment further as needed.
