### ISSUE TITLE
@returns {void} does not require a description but @returns {Promise<void>} does

### ISSUE THREAD

**Issue by JamesCushway** [gajus/eslint-plugin-jsdoc#525]
When returning void, no description is required for the return. However, specifying @returns {Promise<void>} it is required to provide a description. I think @returns {Promise<void>} should be treated the same as @returns {void}

**Comment by brettz9** [comment]
I've filed #527. Note, however, that it is not allowing `@returns {Promise}` to be exempted but it is exempting `@returns {Promise<void>}` or `@returns {Promise<undefined>}`. I'm not sure I'd be convinced that a bare `Promise` would not need documentation, since it could be referring to a Promise of other types.
