### ISSUE TITLE
TOC links in README are all broken on NPM

### ISSUE THREAD

**Issue by danielrentz** [gajus/eslint-plugin-jsdoc#707]
When viewing [the NPM page of this package](https://www.npmjs.com/package/eslint-plugin-jsdoc), the table of contents in the README file is useless, none of the links will bring you to the target.

Example:
The page contains a link `https://www.npmjs.com/package/eslint-plugin-jsdoc#eslint-plugin-jsdoc-settings` but the target element is `<a id="user-content-settings" class="anchor" href="#settings" aria-hidden="true">`

BTW, did you ever considered breaking this monster into smaller pieces? :)

**Comment by brettz9** [comment]
Thank you for the report.

Re: breaking it up, as per https://github.com/gajus/eslint-plugin-jsdoc/pull/475#issuecomment-572405495 , this was rejected.

**Comment by brettz9** [comment]
Thanks for the gitdown fix, @gajus! The links now appear to be generally working, but as a result apparently of the document being too large, it seems npmjs.com has truncated the contents, so that rules after `require-param` don't show up at https://www.npmjs.com/package/eslint-plugin-jsdoc  .

What do you think of our using some document generator which may allow for the advantages of smaller loads and less overwhelming data showing per page, but with a search feature which allows searching for a string of text across all the documents? I assume such tools may exist.
