### ISSUE TITLE
Not working with Eslint 8

### ISSUE THREAD

**Issue by brunomacf** [gajus/eslint-plugin-jsdoc#829]
When running with eslint 8 i'm seeing this error:

```
error  This rule cannot yet be supported for ESLint 8; you should either downgrade to ESLint 7 or disable this rule. The possibility for ESLint 8 support is being tracked at https://github.com/eslint/eslint/issues/14745
```

Indeed https://github.com/eslint/eslint/issues/14745 is still open but we have this https://github.com/gajus/eslint-plugin-jsdoc/issues/791 and this https://github.com/gajus/eslint-plugin-jsdoc/pull/792 which makes me think it should be working fine with ESlint 8. Am i missing something?

**Comment by brettz9** [comment]
Note that the error is only for the rule `jsdoc/check-examples`. You have to currently disable that rule (at least until such time as https://github.com/eslint/eslint/issues/14745 may be fixed). Otherwise, ESLint 8 support is fine.

Closing as that should answer, but feel free to comment further as needed.

**Comment by brunomacf** [comment]
Thanks a lot @brettz9!!
