### ISSUE TITLE
Define contexts globally

### ISSUE THREAD

**Issue by ilyub** [gajus/eslint-plugin-jsdoc#857]
## Motivation

jsdoc plugin has around 20 rules that have "contexts" setting.

Is it possible to globally set default "contexts" for all rules that use this setting?

## Current behavior

I had to discover which rules have "contexts" and configure each of them.

## Desired behavior

I would prefer to have some global "contexts" configuration.

**Comment by brettz9** [comment]
Yes, I think we could allow any `settings.jsdoc.contexts` contexts to be automatically added though while still allowing those individual options--since a project might not want every rule to behave the same.

The `jsdoc/require-jsdoc` rule has its own additional property allowed on the `contexts` objects (used to indicate whether the JSDoc block to be created by our fixer should be inline or not), so our global `settings` contexts should allow that extra property, even though the other rules will not use this extra property.

Similarly, the rule `no-missing-syntax` has additional properties which we might safely ignore. Since the user wants these structures present, perhaps it is safe to insist that a `no-missing-syntax` context added globally as a `settings` context could be shared among other contexts for use by any rule.

However, in the case of the `no-restricted-syntax` rule, its `contexts` would not want to be obtained from the global `contexts` since that rule is *prohibiting* structures in a given context.
