### ISSUE TITLE
Failed to load plugin 'jsdoc' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-jsdoc'

### ISSUE THREAD

**Issue by JoernBerkefeld** [gajus/eslint-plugin-jsdoc#883]
## Expected behavior
The plugin should run like it does when executing eslint --fix
I don't get error messages about the rest - just this one.

## Actual behavior
[Info  - 16:32:27] Failed to load plugin 'jsdoc' declared in '.eslintrc.json': Cannot find module 'eslint-plugin-jsdoc' Require stack: - C:\Git\sfmc-devtools\__placeholder__.js Referenced from: C:\Git\sfmc-devtools\.eslintrc.json
![image](https://user-images.githubusercontent.com/1917227/165111543-b46a13ee-ce70-42b8-bf3a-5e3993c14e98.png)

## ESLint Config

```js
{
    "env": {
        "es6": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "ssjs",
        "plugin:jsdoc/recommended",
        "plugin:prettier/recommended"
    ],
    "plugins": [],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2020,
        "sourceType": "module"
    },
    "rules": {
        "arrow-body-style": ["error", "as-needed"],
        "curly": "error",
        "no-console": "off",
        "require-jsdoc": [
            "warn",
            {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true,
                    "ArrowFunctionExpression": false,
                    "FunctionExpression": true
                }
            }
        ],
        "valid-jsdoc": "error",
        "spaced-comment": ["warn", "always", { "block": { "exceptions": ["*"], "balanced": true } }]
    },
    "overrides": [
        {
            "files": ["*.js"],
            "rules": {
                "no-var": "error",
                "prefer-const": "error",
                "prettier/prettier": "warn",
                "prefer-arrow-callback": "warn"
            }
        }
    ]
}

```

## ESLint sample

The VSCode plugin for ESLint cannot find the plugin despite it being installed

## Environment

- Node version: v16.14.2
- ESLint version v8.12.0 (local install)
- `eslint-plugin-jsdoc` version: 38.0.8 (local install)

**Comment by brettz9** [comment]
Hmmm.. I suspect this may be either an ESLint or VSCode plugin bug, as the plugin is working in other environments. You might try updating to the latest version of `eslint-plugin-jsdoc` (currently 39.2.8), but I don't know what difference that should make.

I can mention the unrelated points that if you do get `eslint-plugin-jsdoc` loaded successfully, you should change `require-jsdoc` to `jsdoc/require-jsdoc` and remove `valid-jsdoc` since ESLint's JSDoc rules are deprecated and we have equivalents for them. (You can see the equivalents at https://github.com/gajus/eslint-plugin-jsdoc/wiki/Comparison-with-deprecated-JSdoc-related-ESLint-rules .)

But of course, hopefully the source of the problem can be discovered so you can use the plugin in the first place.

**Comment by brettz9** [comment]
Closing as I don't believe this should be a plugin-specific issue, but feel free to provide more info if you update to the latest versions, still see the problem, and can provide a minimal test repo.

**Comment by JoernBerkefeld** [comment]
one week and several more restarts later (system and VSCode) that problem somehow solved itself. sorry for bothering you with it

**Comment by brettz9** [comment]
No worries, and glad to hear it worked out
