### ISSUE TITLE
Is an jsdoc/no-extra-parens rule planned?

### ISSUE THREAD

**Issue by Mouvedia** [gajus/eslint-plugin-jsdoc#913]
## Question

Is eslint/eslint#11109 covered by this plugin?

e.g.
```
    'no-extra-parens': 0,
    'jsdoc/no-extra-parens': [1, 'all', {
      'returnAssign': false,
      'enforceForNewInMemberExpressions': false
    }],
```

**Comment by brettz9** [comment]
Although I very much see the need for this, I don't think we want to widen our project's scope to have to maintain rules which include (numerous) behaviors unrelated to JSDoc specifically.

If a rule were instead proposed to insist that any inline JSDoc typecasting blocks (with a `@type` tag) add parentheses around the subsequent item, so that the following:

```js
console.log(/** @type {B} */ d.name);
```

...would report an error, I would be in favor of that as a rule as it seems to be required for TypeScript.

But I think getting involved with rules that check regular JavaScript without being related to JSDoc tags might be more suitable in a plugin oriented toward TypeScript needs. I wonder if in fact [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin) in fact already has the support you are seeking in its rule, [@typescript-eslint/no-extra-parens](https://typescript-eslint.io/rules/no-extra-parens).

Closing though feel free to comment further as needed.

**Comment by Mouvedia** [comment]
> I wonder if in fact [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin?rgh-link-date=2022-09-15T12%3A58%3A29Z) in fact already has the support you are seeking in its rule, [@typescript-eslint/no-extra-parens](https://typescript-eslint.io/rules/no-extra-parens).

Nop, jsdoc inline casting can also be used in js files.

> Although I very much see the need for this…

I guess it will require a separate plugin then.

**Comment by brettz9** [comment]
> > I wonder if in fact [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin?rgh-link-date=2022-09-15T12%3A58%3A29Z) in fact already has the support you are seeking in its rule, [@typescript-eslint/no-extra-parens](https://typescript-eslint.io/rules/no-extra-parens).
> 
> Nop, jsdoc inline casting can also be used in js files.

I'm aware, but using that plugin should also work with plain JavaScript. In any case, it may provide the code that can be used in a plug-in.

> > Although I very much see the need for this…
> 
> I guess it will require a separate plugin then.

Sure. If you put something together, feel free to submit to [awesome-eslint](https://github.com/dustinspecker/awesome-eslint).
